### ISSUE TITLE
[ Cryllic character support ] [ UTF-8 ]Only searches in some specific places 

### ISSUE THREAD

**Issue by x09** [joshinryz/ansible_ldap_inventory#17] opened 2021-03-02 07:07 UTC
I have few OU with computers, something like this

```
├──Company
│  ├──Компьютеры
│  │  ├──test_system
│  │  ├──virtual
│  │  └──2del
│  ├──Компьютеры_P9
│  ├──Компьютеры_Linux
│  ├──Компьютеры_SP
```
if i set **search_ou**: 'OU=Company,DC=adm,DC=local' in ldap_inventory.yml 

```
plugin: ldap_inventory
domain: 'ldap://pdc.adm.local'
port: 3268
auth_type: simple
username: 'cn=view,ou=LDAP,ou=Special,dc=adm,dc=local'
password: pas$$word
search_ou: 'OU=Company,DC=adm,DC=local'
ldap_filter: '(objectClass=computer)'
```

i get computers only from _test_system_, _virtual_, _2del_ groups.. not from parent _Компьютеры_

if i set, for example, **search_ou**: 'OU=Компьютеры_P9,OU=Company,DC=adm,DC=local' i get NOTHING..

```
ansible-inventory -i ldap_inventory.yml --list 
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```
tried ldapsearch in linux console - all work fine.. but ldap_invenotry not searching..
all computers have ObjectClass=computer.. all fields valid, but..

**Comment by joshinryz** [comment] 2021-03-02 15:51
Hello - do you get the same results on port 3269? As Port 3268 is used for queries specifically targeted for the global catalog. LDAP requests sent to port 3268 can be used to search for objects in the entire forest. However, only the attributes marked for replication to the global catalog can be returned. For example, a user’s department could not be returned using port 3268 since this attribute is not replicated to the global catalog.

**Comment by x09** [comment] 2021-03-02 16:46
3268, 3269, 389 - identical output. Аrom test_system, virtual, 2del groups only.
Other groups get 
```

{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}

```

**Comment by joshinryz** [comment] 2021-03-02 16:58
Can you give me full debug output.

**Comment by x09** [comment] 2021-03-02 17:44
full debug very long..

i see many lines like this
```
 3742 1614706605.45465: DEBUG: No OUs were detected in CN=comp-SED-20,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45486: DEBUG: No OUs were detected in CN=comp-DIR-01,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45503: DEBUG: No OUs were detected in CN=comp-S112-BD,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45530: DEBUG: No OUs were detected in CN=comp-UPAITP-01,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45552: DEBUG: No OUs were detected in CN=comp-YUR-01,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45574: DEBUG: No OUs were detected in CN=comp-SMEV-09,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45597: DEBUG: No OUs were detected in CN=comp-SECUR-05,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45616: DEBUG: No OUs were detected in CN=comp-s112-10,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45636: DEBUG: No OUs were detected in CN=comp-ood-09,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45656: DEBUG: No OUs were detected in CN=comp-OSA-03,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45677: DEBUG: No OUs were detected in CN=comp-PR-04,OU=Отключенные,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45701: DEBUG: No OUs were detected in CN=comp-SMEV-14,OU=Отключенные,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45720: DEBUG: No OUs were detected in CN=comp-SMEV-01,OU=Отключенные,OU=Компьютеры,OU=Company,DC=adm,DC=local
  3742 1614706605.45738: DEBUG: No OUs were detected in CN=comp-secur-09,OU=Отключенные,OU=Компьютеры,OU=Company,DC=adm,DC=local
```
and this
` DEBUG: Skipping an possible corrupt object {'name': [b'comp-DIR-1']} CN=comp-DIR-1,OU=Отключенные,OU=Компьютеры,OU=Company,DC=adm,DC=local
`

**Comment by joshinryz** [comment] 2021-03-02 21:23
Yah, this looks to be a regex issue. 

`foundOUs = re.findall('OU=([A-Za-z0-9_ ]{1,})',ouString)`

I'm not familiar with non-ascii characters for languages other than English.

Do you know what the correct regex would be?

**Comment by joshinryz** [comment] 2021-03-02 21:42
Ah ok - can you try this for testing: 
`foundOUs = re.findall('(?u)OU=(\w{1,})',ouString)`

**Comment by x09** [comment] 2021-03-03 09:43
> Ah ok - can you try this for testing:
> `foundOUs = re.findall('(?u)OU=(\w{1,})',ouString)`

Working! But ...
**search_ou**: 'OU=Компьютеры_Linux_Alt_P9,OU=ГКУ ЦИТТО,OU=Советская 61,DC=adm,DC=local'

```
ansible-inventory -i ldap_inventory.yml --list

{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped",
            "\u0441\u043e\u0432\u0435\u0442\u0441\u043a\u0430\u044f"
        ]
    },
    "\u0441\u043e\u0432\u0435\u0442\u0441\u043a\u0430\u044f": {
        "children": [
            "\u0441\u043e\u0432\u0435\u0442\u0441\u043a\u0430\u044f_\u0433\u043a\u0443"
        ]
    },
    "\u0441\u043e\u0432\u0435\u0442\u0441\u043a\u0430\u044f_\u0433\u043a\u0443": {
        "children": [
            "\u0441\u043e\u0432\u0435\u0442\u0441\u043a\u0430\u044f_\u0433\u043a\u0443_\u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u044b_linux_alt_p9"
        ]
    },
    "\u0441\u043e\u0432\u0435\u0442\u0441\u043a\u0430\u044f_\u0433\u043a\u0443_\u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u044b_linux_alt_p9": {
        "hosts": [
            "altp9-ansible-node1.adm.local",
            "altp9-ansible-node2.adm.local",
            "altp9-ansible-node4.adm.local",
            "altp9-ansible-node5.adm.local",
        ]
    }
}
```

```
printf '\u0441\u043e\u0432\u0435\u0442\u0441\u043a\u0430\u044f_\u0433\u043a\u0443_\u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u044b_linux_alt_p9'

советская_гку_компьютеры_linux_alt_p9
```
strange name ;)

**Comment by joshinryz** [comment] 2021-03-03 15:01
The documentation points out that the yaml file must end in ldap_inventory.[yaml|yml] . As for resolving your Cryllic character support, this will require some more research on my part. As I'm guessing I will need to convert the entire codes string handling to UTF-8. 

There is a likelihood I will break python 2 compatibility. If that's the case, these changes will need to wait to merge until Ansible drops Python 2 support.

Anyhow, in the meantime - I'll start looking into this and see how hard it is to do. You can also submit a PR (pull request) if ha ve a resolve version.  If I get it working, I'll add a dev branch with UTF-8 support which you can test.

**Comment by x09** [comment] 2021-03-03 17:15
The problem is probably not only in the Cyrillic alphabet. The problem is also in any non-Latin characters, any alphabets. 
And also with diacritics - Turkish, French, Spanish, Portuguese, German, Italian, Dutch, Swedish, Finnish, Danish, Polish, Czech, Hungarian, Slovenian, Slovak, Estonian, Latvian, Lithuanian, Maltese, Romanian, Vietnamese and so on ;) 

I will wait for a successful resolution of the problem.

I tried using the project https://github.com/mdhowle/ansible-ad-inventory, everything is fine with Cyrillic, but very poor configuration.

**Comment by joshinryz** [comment] 2021-03-04 15:24
Ok, I have the patch done and testing. @x09 as a note, the output you see is from json python. According to the devs this is expected behavior to see the non-ascii characters escaped. 

From Ansible dev:
`default for the json python library is to escape non-ascii characters, and convert them to unicode.  So that is expected. If ensure_ascii is true (the default), the output is guaranteed to have all incoming non-ASCII characters escaped. If ensure_ascii is false, these characters will be output as-is.`

I should have the patch pushed today as it appears non-breaking and backwards compatible.

**Comment by joshinryz** [comment] 2021-03-05 21:31
This has been merged.

**Closed** 2021-03-05 21:31 UTC
